Window.SetBackgroundTopColor(0, 0, 0);
Window.SetBackgroundBottomColor(0, 0, 0);

logo_image = Image("mello-logo-boot.png");

logo_sprite = Sprite();
logo_sprite.SetImage(logo_image);

logo_sprite.SetX(
    Window.GetX() +
    (Window.GetWidth() - logo_image.GetWidth()) / 2
);

logo_sprite.SetY(
    Window.GetY() +
    (Window.GetHeight() - logo_image.GetHeight()) / 2
);

fun refresh_callback() {}
Plymouth.SetRefreshFunction(refresh_callback);